/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mardpop.rocketgui;

/**
 *
 * @author mariu
 */
public class RocketGui extends javax.swing.JFrame {

    /**
     * Creates new form MainApp
     */
    public RocketGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabsContainer = new javax.swing.JTabbedPane();
        DesignPane = new javax.swing.JSplitPane();
        RocketPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textField1 = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        StagesBox = new javax.swing.JComboBox<>();
        AddStageButton = new javax.swing.JButton();
        DeleteStageButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        RocketInfo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        DisplayRocketName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DisplayNumberStages = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        StagePane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SimulationPane = new javax.swing.JScrollPane();
        ResultsPane = new javax.swing.JScrollPane();
        TopMenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        FileNewItem = new javax.swing.JMenuItem();
        FileOpenItem = new javax.swing.JMenuItem();
        FileSaveItem = new javax.swing.JMenuItem();
        OptionsMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));

        DesignPane.setDividerLocation(200);
        DesignPane.setDividerSize(2);
        DesignPane.setLastDividerLocation(200);

        RocketPane.setBackground(new java.awt.Color(255, 255, 255));
        RocketPane.setPreferredSize(new java.awt.Dimension(200, 548));

        jLabel1.setText("Rocket Name");

        textField1.setText("New Rocket");

        jLabel2.setText("Stages");

        AddStageButton.setText("New Stage");

        DeleteStageButton.setText("Delete");

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        RocketInfo.setBackground(new java.awt.Color(255, 255, 255));
        RocketInfo.setLayout(new java.awt.GridLayout(20, 2));

        jLabel3.setText("Rocket Information");
        RocketInfo.add(jLabel3);

        DisplayRocketName.setText("jLabel4");
        RocketInfo.add(DisplayRocketName);

        jLabel4.setText("Number of Stages: ");
        RocketInfo.add(jLabel4);

        DisplayNumberStages.setText("jLabel5");
        RocketInfo.add(DisplayNumberStages);

        jLabel5.setText("Wet Mass");
        RocketInfo.add(jLabel5);

        jScrollPane2.setViewportView(RocketInfo);

        javax.swing.GroupLayout RocketPaneLayout = new javax.swing.GroupLayout(RocketPane);
        RocketPane.setLayout(RocketPaneLayout);
        RocketPaneLayout.setHorizontalGroup(
            RocketPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RocketPaneLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jSeparator1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RocketPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RocketPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RocketPaneLayout.createSequentialGroup()
                        .addComponent(StagesBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddStageButton))
                    .addGroup(RocketPaneLayout.createSequentialGroup()
                        .addGroup(RocketPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(DeleteStageButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        RocketPaneLayout.setVerticalGroup(
            RocketPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RocketPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RocketPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StagesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddStageButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeleteStageButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        DesignPane.setLeftComponent(RocketPane);

        javax.swing.GroupLayout StagePaneLayout = new javax.swing.GroupLayout(StagePane);
        StagePane.setLayout(StagePaneLayout);
        StagePaneLayout.setHorizontalGroup(
            StagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );
        StagePaneLayout.setVerticalGroup(
            StagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        DesignPane.setRightComponent(StagePane);

        TabsContainer.addTab("Design", DesignPane);
        TabsContainer.addTab("Simulation", SimulationPane);
        TabsContainer.addTab("Results", ResultsPane);

        FileMenu.setText("File");

        FileNewItem.setText("New");
        FileMenu.add(FileNewItem);

        FileOpenItem.setText("Open");
        FileMenu.add(FileOpenItem);

        FileSaveItem.setText("Save");
        FileMenu.add(FileSaveItem);

        TopMenuBar.add(FileMenu);

        OptionsMenu.setText("Options");
        TopMenuBar.add(OptionsMenu);

        setJMenuBar(TopMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabsContainer)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TabsContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RocketGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RocketGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RocketGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RocketGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RocketGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddStageButton;
    private javax.swing.JButton DeleteStageButton;
    private javax.swing.JSplitPane DesignPane;
    private javax.swing.JLabel DisplayNumberStages;
    private javax.swing.JLabel DisplayRocketName;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem FileNewItem;
    private javax.swing.JMenuItem FileOpenItem;
    private javax.swing.JMenuItem FileSaveItem;
    private javax.swing.JMenu OptionsMenu;
    private javax.swing.JScrollPane ResultsPane;
    private javax.swing.JPanel RocketInfo;
    private javax.swing.JPanel RocketPane;
    private javax.swing.JScrollPane SimulationPane;
    private javax.swing.JPanel StagePane;
    private javax.swing.JComboBox<String> StagesBox;
    private javax.swing.JTabbedPane TabsContainer;
    private javax.swing.JMenuBar TopMenuBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
